---
title: "iDynoMiCS 2 meeting"
output: html_document
csl: american-physics-society.csl
---

present: Robert, Stefan, Bas

### Agenda:

Diffusion issues
Case studies

### Diffusion

- now stable on non-cartesian grids.
- Investigating maximum time-step

Stefan currently implements:
$$ \frac{1}{var.getMin(DIFFUSIVITY) * var.getShape().getMaxFluxPotential() * 3}$$

Rob:

$$\frac{1}{Diffusivity_{max} * flux_{potential.max}}$$

CFL condition, must be strictly less than? (check)

- explicit solver is very slow, additional solvers can be implemented post publication.

- Stefan will check time step and conditions
- Non zero minimum dimensions

- Rob will look into the diffusivity

- Bas will look into agents in non-cartesian domains

- thinking about setting multiple diffusivity regions

### case studies

meeting Thursday at 14.00 on case studies 

multi compartment?

digester coupled with nitrogen removal

### discussion

bounding volumes non-cartesian domains

- Bas and Stefan will look into issues together